/**
 * Normalizes nginx config for comparison against a baseline.
 *
 * The parity gate exists to catch *behavior* changes. Comments and whitespace
 * are documentation, not behavior, so they are removed before comparing. That
 * lets templates carry better comments than the bash heredocs they replace
 * without every wording change reading as a config change.
 *
 * What is deliberately NOT done: directives are never reordered. Order is
 * semantically significant in nginx (`location` matching, `add_header`
 * inheritance, first-listed `server` becoming the default). A comparison that
 * sorted lines would pass a reordering that genuinely changed behavior.
 */

/**
 * Removes an unquoted `#` comment from one line.
 *
 * Quote-aware rather than a plain `/#.*$/` replace: a `#` inside a quoted nginx
 * value is data, not a comment. No current config has one, but `add_header`
 * values and `map` directives are exactly where one would eventually appear, and
 * silently truncating such a line would corrupt the comparison rather than fail
 * it.
 */
export function stripInlineComment(line: string): string {
  let quote: '"' | "'" | null = null;

  for (let i = 0; i < line.length; i += 1) {
    const char = line[i]!;

    if (char === '\\') {
      i += 1;
      continue;
    }

    if (quote !== null) {
      if (char === quote) quote = null;
      continue;
    }

    if (char === '"' || char === "'") {
      quote = char;
      continue;
    }

    if (char === '#') {
      return line.slice(0, i);
    }
  }

  return line;
}

/**
 * Reduces a config file to its semantically significant lines.
 *
 * Drops comments (whole-line and trailing), trailing whitespace, and blank
 * lines. Leading indentation is preserved: it carries no meaning to nginx, but
 * keeping it makes a failing diff far easier to read, and it cannot mask a
 * behavior change because both sides are generated by the same rules.
 */
export function normalizeNginxConfig(source: string): string {
  return source
    .split('\n')
    .map((line) => stripInlineComment(line).trimEnd())
    .filter((line) => line.length > 0)
    .join('\n');
}
